### ISSUE TITLE
Improve the syntax highlighting for ShellScripts (sh bash scripts)

### ISSUE THREAD

**Issue by aeschli** [textmate/shellscript.tmbundle#38]
_From @qizhuli on April 3, 2017 17:44_

Currently, the syntax highlighting for .sh files that comes with VSCode are inconsistent in the sense that the same thing can be highlighted in different colours, and does not always highlight different types of codes in different colour.
- VSCode Version: 1.9.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Make a .sh file containing the following codes:
```
#!/bin/bash
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
echo $LD_LIBRARY_PATH > ${SCRIPTPATH}/so.path
export MATLABPATH="${SCRIPTPATH}:${MATLABPATH}"
matlab -nodisplay -r "auto_test"
```

Sreenshots of the above codes as shown through VSCode (I am using Icehunter's theme):
![screenshot from 2017-04-03 18 27 21](https://cloud.githubusercontent.com/assets/15232694/24622334/92f258a2-189c-11e7-89b7-945712cd3c38.png)
It can be seen that `${SCRIPTPATH}` was not highlighted in line 4, and highlighted in green in line 5 due to the double quotes around it. 
In comparison, this is the same code rendered by vim:
![screenshot from 2017-04-03 18 29 49](https://cloud.githubusercontent.com/assets/15232694/24622397/ccdbbf54-189c-11e7-9954-82d5a3250ced.png)
Variable expansions are consistently coloured, and different types of keywords are coloured differently.

_Copied from original issue: Microsoft/vscode#23868_

**Comment by mkhl** [comment]
> It can be seen that `${SCRIPTPATH}` was not highlighted in line 4, and highlighted in green in line 5 due to the double quotes around it.

Both of those instances are recognised consistently (and correctly) as `variable.other.bracket.shell`. If they’re not being coloured correctly, please contact the theme author and let them know.
They might want to also fix `variable.other.normal.shell`, like `$LD_LIBRARY_PATH` on line 4.

**Comment by avelis26** [comment]
smh...Why is it EVERY single time... literally EVERY time I find something wrong with VS code and I goto open a bug, I find that a bug has already been opened, AND CLOSED, by some idiot who always uses the excuse of "that's by design" or "we don't have control over that"! Guess what... at a certain point, it's called a BAD DESIGN!!! This user gave you perfect input / output examples demonstrating VS Code sucks in yet another particular way... and you said blame the "author." The author is YOU, Microsoft. https://code.visualstudio.com/ says its a product developed by MICROSOFT! Bash syntax highlighting isn't an extension you install from some 3rd party author, its baked in. Quit trying to blame others for your shitty work and just DO the work! And if there truly is a 3rd party author responsible for the theme, then YOU redirect this bug to them. Why even bug tracking if you're going to ignore all the bugs reported.
At this point, I and many many many many others feel the team developing VS Code should be fired! Still to this date, pressing the up arrow inside the integrated terminal while debugging PowerShell scripts is broken. And guess what... if you go look up that bug, you'll find yet again some idiot saying "oh we don't control that extension, you need to file a bug with that team" ... even though we are talking about POWERSHELL and a feature that has existed in every other terminal since the dawn of time. ACCOUNTABILITY.... look it up.
