### ISSUE TITLE
Here strings (`<<<`) cause syntax highlight issues with command substitution

### ISSUE THREAD

**Issue by dnicolson** [textmate/shellscript.tmbundle#51]
[Here strings](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Here-Strings) (`<<<`) when used with [command substitution](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Command-Substitution-1) cause two issues:
- The closing bracket (`)`) is a different color to the opening one
- The use of backticks (`` ` ``) results in improper syntax highlighting on the lines below

```bash
#!/bin/bash

echo one two
cat <<< $(echo one two)
echo one two

echo one two
cat <<< `echo one two`
echo one two

echo one two
cat <<< $(echo one two)
echo one two
```

<img width="496" alt="Screenshot 2022-09-10 at 20 10 09" src="https://user-images.githubusercontent.com/2276355/189496305-9fb813d8-132a-4636-aae0-a667bcaa615d.png">

**Comment by mkhl** [comment]
nice catch!
currently after the here string operator we only recognize either rather simple strings or barewords so i expect the grammar to also fail for sufficiently complicated variable substitutions.
it might make more sense to drop those rules altogether, i.e. recognize the `<<<` but let the regular shell grammar take back over immediately after, since we can't reliably detect where the actual here string _ends_ :thinking: 

my availability is kind of limited right now, would you consider submitting a pr?

for completeness' sake i should point out that here strings with command substitutions don't make a lot of semantic sense since `foo <<<$(bar)` is equivalent to `bar | foo`, and that you should generally quote command substitutions (although bash doesn't seem to apply word splitting here :shrug:), but that's not what this issue is about :vulcan_salute:

**Comment by dnicolson** [comment]
I guess I could try a bit later, I don't have experience with `.tmLanguage` files so it's not immediately obvious to me where to make the changes.

**Comment by mkhl** [comment]
i found some time to do it, could you check if cd4cf53 works for you?

**Comment by dnicolson** [comment]
It works, thanks for the quick fix!
